import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(fileURLToPath(new URL("..", import.meta.url)));

const required = [
  "README.md",
  "DOWNLOADS.md",
  "QUICKSTART.md",
  "COMMERCIAL.md",
  "LAUNCH_CHECKLIST.md",
  "MANIFEST.md",
  "START_HERE.txt",
  "START.bat",
  "START.sh",
  "SUPPORT.bat",
  "SUPPORT.sh",
  "Dockerfile",
  "docker-compose.yml",
  "docker-compose.full.yml",
  "railway.json",
  "render.yaml",
  "vercel.json",
  "tools/bootstrap.mjs",
  "tools/doctor.mjs",
  "tools/open-browser.mjs",
  "tools/preflight.mjs",
  "tools/support-report.mjs",
  "tools/promo-pack.mjs",
  "tools/wizard.mjs",
  "tools/production-check.mjs",
  "docs/preview.svg",
  "scripts/write-checksums.mjs",
  "scripts/verify-checksums.mjs",
  "src/app.js",
  "api/index.js",
  "public/chatgpt.html",
  "public/claude.html",
  "public/admin.html",
  "public/sitemap.xml",
  "public/assets/growth.css",
  "public/guides/three-minute-chatgpt-gateway.html",
  "public/compare/ai-api-pricing.html",
  "public/compare/gpt-vs-claude.html",
  "public/compare/china-vs-us-models.html",
  "public/tools/api-cost-calculator.html",
  "tools/utm-builder.mjs",
  "site-templates/gpt-tutorial-site/index.html",
  "site-templates/gpt-tutorial-site/site.css",
  "site-templates/claude-tutorial-site/index.html",
  "site-templates/claude-tutorial-site/site.css",
  "site-templates/ai-tools-nav/index.html",
  "site-templates/ai-tools-nav/site.css",
  "growth/github-fork-targets.md",
  "growth/content-calendar.md",
  "growth/reddit-experience-post.md",
  "growth/short-video-scripts.md",
  "growth/comparison-headlines.md",
  "growth/amazon-voucher-plan.md",
  "growth/seo-site-network-plan.md",
  "growth/fork-adapter-template.md",
  "growth/distribution-matrix.md",
  "growth/devto-article-draft.md",
  "growth/hacker-news-draft.md",
  "growth/generated-promo-pack.example.json",
  "growth/approved-action-queue.md",
  "apps/chatgpt-web/package.json",
  "apps/chatgpt-web/Dockerfile",
  "apps/chatgpt-web/vercel.json",
  "apps/chatgpt-web/SUPPORT.bat",
  "apps/chatgpt-web/SUPPORT.sh",
  "apps/chatgpt-web/support-report.mjs",
  "apps/chatgpt-web/public/index.html",
  "apps/claude-web/package.json",
  "apps/claude-web/Dockerfile",
  "apps/claude-web/vercel.json",
  "apps/claude-web/SUPPORT.bat",
  "apps/claude-web/SUPPORT.sh",
  "apps/claude-web/support-report.mjs",
  "apps/claude-web/public/index.html",
  "clients/codex/install.mjs",
  "clients/codex/preflight.mjs",
  "clients/codex/SUPPORT.bat",
  "clients/codex/SUPPORT.sh",
  "clients/codex/support-report.mjs",
  "clients/codex/config.example.json",
  "clients/openclaw/install.mjs",
  "clients/openclaw/preflight.mjs",
  "clients/openclaw/SUPPORT.bat",
  "clients/openclaw/SUPPORT.sh",
  "clients/openclaw/support-report.mjs",
  "clients/openclaw/config.example.json",
];

const missing = required.filter((file) => !fs.existsSync(path.join(root, file)));

if (missing.length) {
  console.error("Missing required package files:");
  for (const file of missing) console.error(`- ${file}`);
  process.exit(1);
}

console.log(JSON.stringify({ ok: true, checked: required.length }, null, 2));
